# Generated by Django 5.0 on 2023-12-05 11:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Location",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("location_name", models.CharField(max_length=256)),
                ("gps", models.CharField(max_length=256)),
            ],
        ),
        migrations.CreateModel(
            name="Measurement",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("CO2", models.IntegerField()),
                ("NO2", models.IntegerField()),
                ("O3", models.IntegerField()),
                ("PM10", models.IntegerField()),
                ("PM2_5", models.IntegerField()),
                ("DateTime", models.DateTimeField()),
                (
                    "location",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="actAir.location",
                    ),
                ),
            ],
        ),
    ]
