# Generated by Django 5.0 on 2023-12-05 11:32

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("actAir", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="measurement",
            name="CO2",
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name="measurement",
            name="NO2",
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name="measurement",
            name="O3",
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name="measurement",
            name="PM10",
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name="measurement",
            name="PM2_5",
            field=models.FloatField(),
        ),
    ]
