# Generated by Django 5.0 on 2023-12-06 01:52

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("actAir", "0002_alter_measurement_co2_alter_measurement_no2_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="measurement",
            name="DateTime",
            field=models.DateField(),
        ),
    ]
